### ISSUE TITLE
Questions about Performance

### ISSUE THREAD

**Issue by tempNameIsNotRealName** [gzy-rgb/CauseRec#3]
I ran your implement code on Amazon Book dataset provided by https://github.com/THUDM/ComiRec, and the end result is not ideal.

my running cmd is python model.py

The summary of the running results is as follows:

epoch: 13, batch: 6506: 
hit20: 0.08395454394858033recall_20: 0.03713888217071739 , NDCG20: 0.06320809276788833
hit50: 0.13517542987774575recall_50: 0.06281990201031389 , NDCG50: 0.1034369766491349

epoch: 15, batch: 6506:
hit20: 0.08132061093993308recall_20: 0.03462265242545869 , NDCG20: 0.06066785217255794
hit50: 0.12992412947685783recall_50: 0.058689492370708196 , NDCG50: 0.09900092043672239

The above evaluation metrics are much lower than those reported in the paper：

CauseH ： 
hit20: 0.1370recall_20: 0.0623 , NDCG20: 0.1051
hit50: 0.2113recall_50: 0.1018 , NDCG50: 0.1655

 I was wondering whether the difference was made due to my negligence. Looking forward to your reply! Thanks!

**Comment by gzy-rgb** [comment]
Hi, there, I implement CauseRec after reading the paper and can run comparable results to the paper. The code uploaded before was from my personal computer which hasn't been updated by the remote server. Now I update it. Hope it will help you.
