### ISSUE TITLE
Questions about the performance on Gowalla 

### ISSUE THREAD

**Issue by outside-BUPT** [gzy-rgb/CauseRec#4]
Hi, I ran your code on Book dataset, the results were CauseRec comparable to the paper:
hit20: 0.1245 recall_20: 0.0575 , NDCG20: 0.0950
hit50: 0.1999 recall_50: 0.0967, NDCG50: 0.1557

While when I try to run the code on Gowalla dataset, the results are much lower than Y-DNN on the same dataset:
Y-DNN : hit50: 0.5635 recall_50: 0.3767, NDCG50: 0.4157
CauseRec : hit50: 0.4698 recall_50: 0.2834, NDCG50: 0.3014

I was wondering whether the difference was made due to the hypeparameter settings. Would you like to share your experience in tuning hypeparameter , such as which hypeparameter has a greater impact on the results.

Looking forward to your reply! Thanks!

**Comment by gzy-rgb** [comment]
I haven't tried this code on Gowalla before. So I guess maybe your hyperparameters are not the same as the paper, or maybe your Gowalla dataset is different from the paper.
